#[cfg(unix)]
use std::ffi::{OsStr, OsString};
use std::fs;
#[cfg(not(unix))]
use std::fs::OpenOptions;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

#[cfg(any(target_vendor = "apple", target_os = "linux", target_os = "android"))]
use rustix::fs::RenameFlags;
#[cfg(unix)]
use rustix::fs::{AtFlags, Mode, OFlags};
#[cfg(unix)]
use std::os::fd::OwnedFd;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

use crate::error::BelayError;
use crate::repository::Repository;

pub(crate) const START_MARKER: &str = "<!-- belay-trace:start -->";
pub(crate) const END_MARKER: &str = "<!-- belay-trace:end -->";

pub(crate) const AGENT_SNIPPET: &str = r#"<!-- Generated by belay-trace. Activate explicitly; default init does not modify AGENTS.md. -->
<!-- belay-trace:start -->
## belay-trace

- Run `belay context "<task>" --format agent --budget 2500` before broad historical log reads.
- Use `belay search "<query>"` for targeted discovery and `belay show <id>` only when a full entry is needed.
- Use `belay add`, `belay link`, and `belay status <id> <status>` for trace updates.
- Run `belay sync` after direct managed Markdown edits.
- Never overwrite an unresolved sync conflict. Inspect it and use an explicit `belay sync --prefer markdown <id>` or `belay sync --prefer sqlite <id>` only after the intended source of truth is known.
- Do not scan `.belay/entries/` broadly unless a specific source path is required.
<!-- belay-trace:end -->
"#;

pub(crate) const CODEX_SKILL: &str = r#"---
name: belay-trace
description: Use when a task needs project plans, decisions, work history, review context, or trace updates through the local belay CLI.
---

# belay-trace

## Retrieve context

1. Run `belay context "<task>" --format agent --budget 2500` before broad historical reads.
2. Use `belay search "<query>"` for targeted discovery.
3. Use `belay show <id>` only when the full entry is needed.
4. Avoid broad reads of `.belay/entries/` unless a command identifies a specific source path.

## Update trace

1. Use `belay add`, `belay link`, and `belay status <id> <status>` for structured updates.
2. Run `belay sync` after direct managed Markdown edits.
3. Run `belay doctor` when generated or active integration may be stale.

## Conflict safety

Never overwrite an unresolved sync conflict. Inspect both sides and use
`belay sync --prefer markdown <id>` or `belay sync --prefer sqlite <id>` only
after the intended source of truth is known.

Repository-specific policy belongs in the repository `AGENTS.md`, not in this
generic skill.
"#;

pub(crate) const CLAUDE_SKILL: &str = r#"---
name: belay-trace
description: Use when a task needs project plans, decisions, work history, review context, or trace updates through the local belay CLI.
---

# belay-trace

## Retrieve context

1. Run `belay context "<task>" --format agent --budget 2500` before broad historical reads.
2. Use `belay search "<query>"` for targeted discovery.
3. Use `belay show <id>` only when the full entry is needed.
4. Avoid broad reads of `.belay/entries/` unless a command identifies a specific source path.

## Update trace

1. Use `belay add`, `belay link`, and `belay status <id> <status>` for structured updates.
2. Run `belay sync` after direct managed Markdown edits.
3. Run `belay doctor` when generated or active integration may be stale.

## Conflict safety

Never overwrite an unresolved sync conflict. Inspect both sides and use
`belay sync --prefer markdown <id>` or `belay sync --prefer sqlite <id>` only
after the intended source of truth is known.

Repository-specific policy belongs in the repository `CLAUDE.md`, not in this
generic skill.
"#;

const CODEX_SKILL_RELATIVE_PATH: &str = ".agents/skills/belay-trace/SKILL.md";
const CLAUDE_SKILL_RELATIVE_PATH: &str = ".claude/skills/belay-trace/SKILL.md";

#[derive(Debug)]
struct FileSnapshot {
    contents: String,
    permissions: fs::Permissions,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ActivationStatus {
    Created,
    Updated,
    Unchanged,
}

impl ActivationStatus {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Created => "created",
            Self::Updated => "updated",
            Self::Unchanged => "unchanged",
        }
    }
}

#[derive(Debug, Clone)]
pub struct ActivationOutcome {
    pub path: PathBuf,
    pub status: ActivationStatus,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CheckStatus {
    Present,
    Active,
    Inactive,
    Missing,
    Stale,
    Malformed,
}

impl CheckStatus {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Present => "present",
            Self::Active => "active",
            Self::Inactive => "inactive",
            Self::Missing => "missing",
            Self::Stale => "stale",
            Self::Malformed => "malformed",
        }
    }
}

#[derive(Debug, Clone)]
pub struct DoctorCheck {
    pub name: &'static str,
    pub path: PathBuf,
    pub status: CheckStatus,
}

#[derive(Debug, Clone)]
pub struct DoctorReport {
    pub checks: Vec<DoctorCheck>,
    pub has_drift: bool,
    pub has_malformed: bool,
}

pub(crate) fn refresh_generated_assets(repository: &Repository) -> Result<(), BelayError> {
    replace_if_changed(
        &repository.root,
        &repository.belay_dir.join("agent/AGENTS.md.snippet"),
        AGENT_SNIPPET,
    )?;
    replace_if_changed(
        &repository.root,
        &repository.belay_dir.join("agent/codex/SKILL.md"),
        CODEX_SKILL,
    )?;
    replace_if_changed(
        &repository.root,
        &repository.belay_dir.join("agent/claude/SKILL.md"),
        CLAUDE_SKILL,
    )
}

pub fn update_agents(repository: &Repository) -> Result<ActivationOutcome, BelayError> {
    let path = repository.root.join("AGENTS.md");
    let existing = read_optional_regular_file(&path)?;
    let managed = managed_agents_section();
    let (rendered, status) = match existing.as_ref() {
        None => (format!("{managed}\n"), ActivationStatus::Created),
        Some(existing) => update_managed_section(&existing.contents, managed)?,
    };

    if status != ActivationStatus::Unchanged {
        safe_write(
            &repository.root,
            &path,
            rendered.as_bytes(),
            existing.as_ref(),
        )?;
    }
    Ok(ActivationOutcome { path, status })
}

pub fn install_codex_skill(repository: &Repository) -> Result<ActivationOutcome, BelayError> {
    install_skill(
        repository,
        Path::new(CODEX_SKILL_RELATIVE_PATH),
        CODEX_SKILL,
    )
}

pub fn install_claude_skill(repository: &Repository) -> Result<ActivationOutcome, BelayError> {
    install_skill(
        repository,
        Path::new(CLAUDE_SKILL_RELATIVE_PATH),
        CLAUDE_SKILL,
    )
}

fn install_skill(
    repository: &Repository,
    relative_path: &Path,
    expected: &str,
) -> Result<ActivationOutcome, BelayError> {
    let path = repository.root.join(relative_path);
    let directory = relative_path
        .parent()
        .expect("agent skill path has a parent directory");
    ensure_safe_directory_tree(&repository.root, directory)?;
    let existing = read_optional_regular_file(&path)?;
    let status = match existing.as_ref() {
        None => ActivationStatus::Created,
        Some(existing) if existing.contents == expected => ActivationStatus::Unchanged,
        Some(_) => ActivationStatus::Updated,
    };
    if status != ActivationStatus::Unchanged {
        safe_write(
            &repository.root,
            &path,
            expected.as_bytes(),
            existing.as_ref(),
        )?;
    }
    Ok(ActivationOutcome { path, status })
}

pub fn doctor(repository: &Repository) -> Result<DoctorReport, BelayError> {
    let generated_snippet = check_exact_file(
        "generated AGENTS snippet",
        repository.belay_dir.join("agent/AGENTS.md.snippet"),
        AGENT_SNIPPET,
        CheckStatus::Present,
    )?;
    let generated_skill = check_exact_file(
        "generated Codex skill",
        repository.belay_dir.join("agent/codex/SKILL.md"),
        CODEX_SKILL,
        CheckStatus::Present,
    )?;
    let generated_claude_skill = check_exact_file(
        "generated Claude skill",
        repository.belay_dir.join("agent/claude/SKILL.md"),
        CLAUDE_SKILL,
        CheckStatus::Present,
    )?;
    let agents = check_agents(repository)?;
    let installed_skill = check_exact_file(
        "installed Codex skill",
        repository.root.join(CODEX_SKILL_RELATIVE_PATH),
        CODEX_SKILL,
        CheckStatus::Active,
    )?;
    let installed_claude_skill = check_exact_file(
        "installed Claude skill",
        repository.root.join(CLAUDE_SKILL_RELATIVE_PATH),
        CLAUDE_SKILL,
        CheckStatus::Active,
    )?;

    let checks = vec![
        generated_snippet,
        agents,
        generated_skill,
        installed_skill,
        generated_claude_skill,
        installed_claude_skill,
    ];
    let has_drift = checks
        .iter()
        .any(|check| matches!(check.status, CheckStatus::Missing | CheckStatus::Stale));
    let has_malformed = checks
        .iter()
        .any(|check| check.status == CheckStatus::Malformed);
    Ok(DoctorReport {
        checks,
        has_drift,
        has_malformed,
    })
}

fn managed_agents_section() -> &'static str {
    AGENT_SNIPPET
        .strip_prefix(
            "<!-- Generated by belay-trace. Activate explicitly; default init does not modify AGENTS.md. -->\n",
        )
        .expect("generated AGENTS snippet has a stable preamble")
        .trim_end()
}

fn update_managed_section(
    existing: &str,
    managed: &str,
) -> Result<(String, ActivationStatus), BelayError> {
    let starts = existing.match_indices(START_MARKER).collect::<Vec<_>>();
    let ends = existing.match_indices(END_MARKER).collect::<Vec<_>>();
    match (starts.as_slice(), ends.as_slice()) {
        ([], []) => {
            let mut rendered = existing.to_owned();
            if !rendered.is_empty() && !rendered.ends_with('\n') {
                rendered.push('\n');
            }
            if !rendered.is_empty() {
                rendered.push('\n');
            }
            rendered.push_str(managed);
            rendered.push('\n');
            Ok((rendered, ActivationStatus::Updated))
        }
        ([(start, _)], [(end, _)]) if start < end => {
            let end = end + END_MARKER.len();
            let current = &existing[*start..end];
            if current == managed {
                return Ok((existing.to_owned(), ActivationStatus::Unchanged));
            }
            let mut rendered =
                String::with_capacity(existing.len() - current.len() + managed.len());
            rendered.push_str(&existing[..*start]);
            rendered.push_str(managed);
            rendered.push_str(&existing[end..]);
            Ok((rendered, ActivationStatus::Updated))
        }
        _ => Err(BelayError::Validation {
            message: format!(
                "AGENTS.md has malformed belay-trace markers; expected exactly one ordered `{START_MARKER}` and `{END_MARKER}` pair"
            ),
        }),
    }
}

fn check_agents(repository: &Repository) -> Result<DoctorCheck, BelayError> {
    let path = repository.root.join("AGENTS.md");
    let Some(existing) = read_optional_regular_file(&path)? else {
        return Ok(DoctorCheck {
            name: "AGENTS.md integration",
            path,
            status: CheckStatus::Inactive,
        });
    };
    let starts = existing
        .contents
        .match_indices(START_MARKER)
        .collect::<Vec<_>>();
    let ends = existing
        .contents
        .match_indices(END_MARKER)
        .collect::<Vec<_>>();
    let status = match (starts.as_slice(), ends.as_slice()) {
        ([], []) => CheckStatus::Inactive,
        ([(start, _)], [(end, _)]) if start < end => {
            let end = end + END_MARKER.len();
            if &existing.contents[*start..end] == managed_agents_section() {
                CheckStatus::Active
            } else {
                CheckStatus::Stale
            }
        }
        _ => CheckStatus::Malformed,
    };
    Ok(DoctorCheck {
        name: "AGENTS.md integration",
        path,
        status,
    })
}

fn check_exact_file(
    name: &'static str,
    path: PathBuf,
    expected: &str,
    matching_status: CheckStatus,
) -> Result<DoctorCheck, BelayError> {
    let status = match read_optional_regular_file(&path)? {
        None if matching_status == CheckStatus::Active => CheckStatus::Inactive,
        None => CheckStatus::Missing,
        Some(existing) if existing.contents == expected => matching_status,
        Some(_) => CheckStatus::Stale,
    };
    Ok(DoctorCheck { name, path, status })
}

fn replace_if_changed(root: &Path, path: &Path, expected: &str) -> Result<(), BelayError> {
    let existing = read_optional_regular_file(path)?;
    if existing
        .as_ref()
        .is_some_and(|snapshot| snapshot.contents == expected)
    {
        return Ok(());
    }
    safe_write(root, path, expected.as_bytes(), existing.as_ref())
}

fn ensure_safe_directory_tree(root: &Path, relative: &Path) -> Result<(), BelayError> {
    #[cfg(unix)]
    {
        ensure_safe_directory_tree_unix(root, relative)
    }

    #[cfg(not(unix))]
    {
        ensure_safe_directory_tree_portable(root, relative)
    }
}

#[cfg(unix)]
fn ensure_safe_directory_tree_unix(root: &Path, relative: &Path) -> Result<(), BelayError> {
    let directory_flags = OFlags::RDONLY | OFlags::DIRECTORY | OFlags::NOFOLLOW | OFlags::CLOEXEC;
    let mut fd = rustix::fs::open(root, directory_flags, Mode::empty())
        .map_err(|source| safe_directory_error(root, source))?;
    let mut current = root.to_path_buf();
    for component in relative.components() {
        let std::path::Component::Normal(component) = component else {
            return Err(BelayError::Validation {
                message: format!(
                    "agent integration path {} must stay within {}",
                    relative.display(),
                    root.display()
                ),
            });
        };
        current.push(component);
        match rustix::fs::openat(&fd, component, directory_flags, Mode::empty()) {
            Ok(next) => fd = next,
            Err(rustix::io::Errno::NOENT) => {
                match rustix::fs::mkdirat(
                    &fd,
                    component,
                    Mode::RWXU | Mode::RGRP | Mode::XGRP | Mode::ROTH | Mode::XOTH,
                ) {
                    Ok(()) | Err(rustix::io::Errno::EXIST) => {}
                    Err(source) => {
                        return Err(unix_io(
                            "create agent integration directory",
                            &current,
                            source,
                        ));
                    }
                }
                fd = rustix::fs::openat(&fd, component, directory_flags, Mode::empty())
                    .map_err(|source| safe_directory_error(&current, source))?;
            }
            Err(source) => return Err(safe_directory_error(&current, source)),
        }
    }
    rustix::fs::fsync(&fd).map_err(|source| unix_io("flush directory", &current, source))
}

#[cfg(not(unix))]
fn ensure_safe_directory_tree_portable(root: &Path, relative: &Path) -> Result<(), BelayError> {
    let mut current = root.to_path_buf();
    for component in relative.components() {
        let std::path::Component::Normal(component) = component else {
            return Err(BelayError::Validation {
                message: format!(
                    "agent integration path {} must stay within {}",
                    relative.display(),
                    root.display()
                ),
            });
        };
        current.push(component);
        match fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(BelayError::Validation {
                    message: format!(
                        "agent integration directory {} must not be a symbolic link",
                        current.display()
                    ),
                });
            }
            Ok(metadata) if metadata.is_dir() => {}
            Ok(_) => {
                return Err(BelayError::Validation {
                    message: format!(
                        "agent integration path {} must be a directory",
                        current.display()
                    ),
                });
            }
            Err(source) if source.kind() == std::io::ErrorKind::NotFound => {
                fs::create_dir(&current)
                    .map_err(|source| BelayError::io("create directory", &current, source))?;
            }
            Err(source) => return Err(BelayError::io("inspect", &current, source)),
        }
    }
    Ok(())
}

fn read_optional_regular_file(path: &Path) -> Result<Option<FileSnapshot>, BelayError> {
    match fs::symlink_metadata(path) {
        Ok(metadata) if metadata.file_type().is_symlink() => Err(BelayError::Validation {
            message: format!(
                "agent integration path {} must not be a symbolic link",
                path.display()
            ),
        }),
        Ok(metadata) if !metadata.is_file() => Err(BelayError::Validation {
            message: format!(
                "agent integration path {} must be a regular file",
                path.display()
            ),
        }),
        Ok(metadata) => {
            let contents =
                fs::read_to_string(path).map_err(|source| BelayError::io("read", path, source))?;
            Ok(Some(FileSnapshot {
                contents,
                permissions: metadata.permissions(),
            }))
        }
        Err(source) if source.kind() == std::io::ErrorKind::NotFound => Ok(None),
        Err(source) => Err(BelayError::io("inspect", path, source)),
    }
}

fn safe_write(
    root: &Path,
    path: &Path,
    contents: &[u8],
    expected: Option<&FileSnapshot>,
) -> Result<(), BelayError> {
    #[cfg(unix)]
    {
        safe_write_unix(root, path, contents, expected)
    }

    #[cfg(not(unix))]
    {
        safe_write_portable(root, path, contents, expected)
    }
}

#[cfg(unix)]
struct SafeParent {
    fd: OwnedFd,
    file_name: OsString,
    path: PathBuf,
}

#[cfg(unix)]
fn safe_write_unix(
    root: &Path,
    path: &Path,
    contents: &[u8],
    expected: Option<&FileSnapshot>,
) -> Result<(), BelayError> {
    let parent = open_safe_parent(root, path)?;
    let temporary = write_temporary_at(&parent, path, contents, expected)?;
    match expected {
        None => publish_new_file(&parent, path, &temporary),
        Some(expected) => publish_replacement(&parent, path, &temporary, expected),
    }
}

#[cfg(unix)]
fn open_safe_parent(root: &Path, path: &Path) -> Result<SafeParent, BelayError> {
    let relative = path
        .strip_prefix(root)
        .map_err(|_| BelayError::Validation {
            message: format!(
                "agent integration path {} must stay within {}",
                path.display(),
                root.display()
            ),
        })?;
    if relative.as_os_str().is_empty()
        || relative
            .components()
            .any(|component| !matches!(component, std::path::Component::Normal(_)))
    {
        return Err(BelayError::Validation {
            message: format!(
                "agent integration path {} must use normal relative components",
                path.display()
            ),
        });
    }
    let file_name = relative
        .file_name()
        .ok_or_else(|| BelayError::Validation {
            message: format!("agent integration path {} has no filename", path.display()),
        })?
        .to_os_string();
    let parent_relative = relative.parent().ok_or_else(|| BelayError::Validation {
        message: format!("agent integration path {} has no parent", path.display()),
    })?;

    let directory_flags = OFlags::RDONLY | OFlags::DIRECTORY | OFlags::NOFOLLOW | OFlags::CLOEXEC;
    let mut fd = rustix::fs::open(root, directory_flags, Mode::empty())
        .map_err(|source| safe_directory_error(root, source))?;
    let mut parent_path = root.to_path_buf();
    for component in parent_relative.components() {
        let std::path::Component::Normal(component) = component else {
            return Err(BelayError::Validation {
                message: format!(
                    "agent integration path {} must use normal relative components",
                    path.display()
                ),
            });
        };
        parent_path.push(component);
        fd = rustix::fs::openat(&fd, component, directory_flags, Mode::empty())
            .map_err(|source| safe_directory_error(&parent_path, source))?;
    }
    Ok(SafeParent {
        fd,
        file_name,
        path: parent_path,
    })
}

#[cfg(unix)]
fn write_temporary_at(
    parent: &SafeParent,
    destination: &Path,
    contents: &[u8],
    expected: Option<&FileSnapshot>,
) -> Result<OsString, BelayError> {
    let file_name = parent
        .file_name
        .to_str()
        .ok_or_else(|| BelayError::Validation {
            message: format!(
                "agent integration path {} has an invalid filename",
                destination.display()
            ),
        })?;
    for attempt in 0..100_u32 {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let temporary = OsString::from(format!(
            ".{file_name}.belay-tmp-{}-{nonce}-{attempt}",
            std::process::id()
        ));
        match rustix::fs::openat(
            &parent.fd,
            &temporary,
            OFlags::WRONLY | OFlags::CREATE | OFlags::EXCL | OFlags::NOFOLLOW | OFlags::CLOEXEC,
            Mode::RUSR | Mode::WUSR | Mode::RGRP | Mode::ROTH,
        ) {
            Ok(fd) => {
                let mut file = fs::File::from(fd);
                let operation = (|| {
                    if let Some(expected) = expected {
                        file.set_permissions(expected.permissions.clone())
                            .map_err(|source| {
                                BelayError::io(
                                    "set temporary file permissions",
                                    destination,
                                    source,
                                )
                            })?;
                    }
                    file.write_all(contents).map_err(|source| {
                        BelayError::io("write temporary file", destination, source)
                    })?;
                    file.sync_all().map_err(|source| {
                        BelayError::io("flush temporary file", destination, source)
                    })
                })();
                drop(file);
                if let Err(error) = operation {
                    let _ = rustix::fs::unlinkat(&parent.fd, &temporary, AtFlags::empty());
                    return Err(error);
                }
                return Ok(temporary);
            }
            Err(rustix::io::Errno::EXIST) => continue,
            Err(source) => return Err(unix_io("create temporary file", destination, source)),
        }
    }
    Err(BelayError::Validation {
        message: format!(
            "could not allocate a temporary file beside {}",
            destination.display()
        ),
    })
}

#[cfg(unix)]
fn publish_new_file(
    parent: &SafeParent,
    path: &Path,
    temporary: &OsString,
) -> Result<(), BelayError> {
    match rustix::fs::linkat(
        &parent.fd,
        temporary,
        &parent.fd,
        &parent.file_name,
        AtFlags::empty(),
    ) {
        Ok(()) => {
            rustix::fs::unlinkat(&parent.fd, temporary, AtFlags::empty())
                .map_err(|source| unix_io("remove temporary file", path, source))?;
            sync_safe_directory(parent)
        }
        Err(source) => {
            let _ = rustix::fs::unlinkat(&parent.fd, temporary, AtFlags::empty());
            if source == rustix::io::Errno::EXIST {
                Err(BelayError::Conflict {
                    message: format!(
                        "agent integration file {} was created concurrently; retry the command",
                        path.display()
                    ),
                })
            } else {
                Err(unix_io("create agent integration file", path, source))
            }
        }
    }
}

#[cfg(any(target_vendor = "apple", target_os = "linux", target_os = "android"))]
fn publish_replacement(
    parent: &SafeParent,
    path: &Path,
    temporary: &OsString,
    expected: &FileSnapshot,
) -> Result<(), BelayError> {
    if let Err(source) = rustix::fs::renameat_with(
        &parent.fd,
        temporary,
        &parent.fd,
        &parent.file_name,
        RenameFlags::EXCHANGE,
    ) {
        let _ = rustix::fs::unlinkat(&parent.fd, temporary, AtFlags::empty());
        return Err(unix_io("exchange agent integration file", path, source));
    }

    let previous_matches = match read_snapshot_at(parent, temporary, path) {
        Ok(previous) => snapshots_match(&previous, expected),
        Err(_) => false,
    };
    if !previous_matches {
        let rollback = rustix::fs::renameat_with(
            &parent.fd,
            temporary,
            &parent.fd,
            &parent.file_name,
            RenameFlags::EXCHANGE,
        );
        if rollback.is_ok() {
            let _ = rustix::fs::unlinkat(&parent.fd, temporary, AtFlags::empty());
            let _ = sync_safe_directory(parent);
            return Err(BelayError::Conflict {
                message: format!(
                    "agent integration file {} changed concurrently; retry after reviewing the latest file",
                    path.display()
                ),
            });
        }
        return Err(BelayError::Conflict {
            message: format!(
                "agent integration file {} changed concurrently and rollback failed; preserve both files before retrying",
                path.display()
            ),
        });
    }

    rustix::fs::unlinkat(&parent.fd, temporary, AtFlags::empty())
        .map_err(|source| unix_io("remove previous agent integration file", path, source))?;
    sync_safe_directory(parent)
}

#[cfg(all(
    unix,
    not(any(target_vendor = "apple", target_os = "linux", target_os = "android"))
))]
fn publish_replacement(
    parent: &SafeParent,
    path: &Path,
    temporary: &OsString,
    expected: &FileSnapshot,
) -> Result<(), BelayError> {
    let current = read_snapshot_at(parent, &parent.file_name, path)?;
    if !snapshots_match(&current, expected) {
        let _ = rustix::fs::unlinkat(&parent.fd, temporary, AtFlags::empty());
        return Err(BelayError::Conflict {
            message: format!(
                "agent integration file {} changed concurrently; retry after reviewing the latest file",
                path.display()
            ),
        });
    }
    if let Err(source) = rustix::fs::renameat(&parent.fd, temporary, &parent.fd, &parent.file_name)
    {
        let _ = rustix::fs::unlinkat(&parent.fd, temporary, AtFlags::empty());
        return Err(unix_io("replace agent integration file", path, source));
    }
    sync_safe_directory(parent)
}

#[cfg(unix)]
fn read_snapshot_at(
    parent: &SafeParent,
    file_name: &OsStr,
    path: &Path,
) -> Result<FileSnapshot, BelayError> {
    let fd = rustix::fs::openat(
        &parent.fd,
        file_name,
        OFlags::RDONLY | OFlags::NOFOLLOW | OFlags::NONBLOCK | OFlags::CLOEXEC,
        Mode::empty(),
    )
    .map_err(|source| unix_io("open agent integration file", path, source))?;
    let mut file = fs::File::from(fd);
    let metadata = file
        .metadata()
        .map_err(|source| BelayError::io("inspect", path, source))?;
    if !metadata.is_file() {
        return Err(BelayError::Validation {
            message: format!(
                "agent integration path {} must be a regular file",
                path.display()
            ),
        });
    }
    let mut contents = String::new();
    file.read_to_string(&mut contents)
        .map_err(|source| BelayError::io("read", path, source))?;
    Ok(FileSnapshot {
        contents,
        permissions: metadata.permissions(),
    })
}

#[cfg(unix)]
fn snapshots_match(left: &FileSnapshot, right: &FileSnapshot) -> bool {
    left.contents == right.contents
        && left.permissions.mode() & 0o7777 == right.permissions.mode() & 0o7777
}

#[cfg(unix)]
fn sync_safe_directory(parent: &SafeParent) -> Result<(), BelayError> {
    rustix::fs::fsync(&parent.fd).map_err(|source| unix_io("flush directory", &parent.path, source))
}

#[cfg(unix)]
fn safe_directory_error(path: &Path, source: rustix::io::Errno) -> BelayError {
    if matches!(source, rustix::io::Errno::LOOP | rustix::io::Errno::NOTDIR) {
        BelayError::Validation {
            message: format!(
                "agent integration path {} must be a real directory, not a symbolic link",
                path.display()
            ),
        }
    } else {
        unix_io("open agent integration directory", path, source)
    }
}

#[cfg(unix)]
fn unix_io(action: &'static str, path: &Path, source: rustix::io::Errno) -> BelayError {
    BelayError::io(
        action,
        path,
        std::io::Error::from_raw_os_error(source.raw_os_error()),
    )
}

#[cfg(not(unix))]
fn safe_write_portable(
    root: &Path,
    path: &Path,
    contents: &[u8],
    expected: Option<&FileSnapshot>,
) -> Result<(), BelayError> {
    if expected.is_some() {
        return Err(BelayError::Capability {
            message: format!(
                "safe replacement of existing agent integration file {} is not supported on this platform",
                path.display()
            ),
        });
    }

    let relative = path
        .strip_prefix(root)
        .map_err(|_| BelayError::Validation {
            message: format!(
                "agent integration path {} must stay within {}",
                path.display(),
                root.display()
            ),
        })?;
    let parent = relative.parent().ok_or_else(|| BelayError::Validation {
        message: format!("agent integration path {} has no parent", path.display()),
    })?;
    let mut current = root.to_path_buf();
    for component in parent.components() {
        let std::path::Component::Normal(component) = component else {
            return Err(BelayError::Validation {
                message: format!(
                    "agent integration path {} must use normal relative components",
                    path.display()
                ),
            });
        };
        current.push(component);
        let metadata = fs::symlink_metadata(&current)
            .map_err(|source| BelayError::io("inspect", &current, source))?;
        if metadata.file_type().is_symlink() || !metadata.is_dir() {
            return Err(BelayError::Validation {
                message: format!(
                    "agent integration path {} must be a real directory",
                    current.display()
                ),
            });
        }
    }

    if read_optional_regular_file(path)?.is_some() {
        return Err(BelayError::Conflict {
            message: format!(
                "agent integration file {} was created concurrently; retry the command",
                path.display()
            ),
        });
    }
    let file_name = path
        .file_name()
        .and_then(|name| name.to_str())
        .ok_or_else(|| BelayError::Validation {
            message: format!(
                "agent integration path {} has invalid filename",
                path.display()
            ),
        })?;
    for attempt in 0..100_u32 {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos();
        let temporary = path.with_file_name(format!(
            ".{file_name}.belay-tmp-{}-{nonce}-{attempt}",
            std::process::id()
        ));
        match OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)
        {
            Ok(mut file) => {
                let operation = (|| {
                    file.write_all(contents).map_err(|source| {
                        BelayError::io("write temporary file", &temporary, source)
                    })?;
                    file.sync_all().map_err(|source| {
                        BelayError::io("flush temporary file", &temporary, source)
                    })
                })();
                drop(file);
                if let Err(error) = operation {
                    let _ = fs::remove_file(&temporary);
                    return Err(error);
                }
                if let Err(source) = fs::hard_link(&temporary, path) {
                    let _ = fs::remove_file(&temporary);
                    if source.kind() == std::io::ErrorKind::AlreadyExists {
                        return Err(BelayError::Conflict {
                            message: format!(
                                "agent integration file {} was created concurrently; retry the command",
                                path.display()
                            ),
                        });
                    }
                    return Err(BelayError::io(
                        "create agent integration file",
                        path,
                        source,
                    ));
                }
                fs::remove_file(&temporary).map_err(|source| {
                    BelayError::io("remove temporary file", &temporary, source)
                })?;
                return Ok(());
            }
            Err(source) if source.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(source) => {
                return Err(BelayError::io("create temporary file", &temporary, source));
            }
        }
    }
    Err(BelayError::Validation {
        message: format!(
            "could not allocate a temporary file beside {}",
            path.display()
        ),
    })
}

#[cfg(test)]
mod tests {
    use tempfile::tempdir;

    use super::*;

    #[test]
    fn managed_section_append_and_replace_preserve_unrelated_content() {
        let managed = managed_agents_section();
        let (appended, status) =
            update_managed_section("# Existing\nKeep this.\n", managed).expect("append section");
        assert_eq!(status, ActivationStatus::Updated);
        assert!(appended.starts_with("# Existing\nKeep this.\n\n"));
        assert!(appended.contains(managed));

        let stale = appended.replace("Use `belay search", "Use stale `belay search");
        let (replaced, status) = update_managed_section(&stale, managed).expect("replace section");
        assert_eq!(status, ActivationStatus::Updated);
        assert!(replaced.starts_with("# Existing\nKeep this.\n\n"));
        assert!(replaced.contains(managed));
        assert!(!replaced.contains("Use stale"));

        let (stable, status) = update_managed_section(&replaced, managed).expect("stable section");
        assert_eq!(status, ActivationStatus::Unchanged);
        assert_eq!(stable, replaced);
    }

    #[test]
    fn malformed_markers_are_rejected() {
        let error = update_managed_section(START_MARKER, managed_agents_section())
            .expect_err("partial markers must fail");
        assert!(matches!(error, BelayError::Validation { .. }));
    }

    #[cfg(unix)]
    #[test]
    fn safe_write_preserves_permissions_and_rejects_concurrent_changes() {
        let temporary = tempdir().expect("create temp directory");
        let root = temporary.path();
        let path = root.join("AGENTS.md");
        fs::write(&path, "before\n").expect("write original");
        fs::set_permissions(&path, fs::Permissions::from_mode(0o600))
            .expect("set original permissions");

        let original = read_optional_regular_file(&path)
            .expect("read original")
            .expect("original exists");
        safe_write(root, &path, b"after\n", Some(&original)).expect("replace original");
        assert_eq!(
            fs::metadata(&path)
                .expect("read metadata")
                .permissions()
                .mode()
                & 0o777,
            0o600
        );

        let expected = read_optional_regular_file(&path)
            .expect("read replacement")
            .expect("replacement exists");
        fs::write(&path, "concurrent\n").expect("write concurrent update");
        let error = safe_write(root, &path, b"lost update\n", Some(&expected))
            .expect_err("concurrent update must be rejected");
        assert!(matches!(error, BelayError::Conflict { .. }));
        assert_eq!(
            fs::read_to_string(&path).expect("read preserved concurrent update"),
            "concurrent\n"
        );
    }
}
